name: Test Deploy Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Echo test
        run: echo "Hello from build step"

      - name: Deploy (dummy)
        run: echo "Deploy step"
