name: Debug Test

on: [push, workflow_dispatch]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1
        run: echo "Hello from step 1"

      - name: Sleep
        run: sleep 5

      - name: Step 2
        run: echo "Hello from step 2"

      - name: Step 2
        run: echo "Is my repo public yet"
